# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 589fceb76a3ba994c6a9b546eef11066636c7c13bffcece49d72d557ef5ef388609e9d592ed19535c900e51811ca2981e17d308d966d268e8237ea5d3b856362

test:
  secret_key_base: fd2530cb297a97c4ee71b8ee4a5c0464f640da8e94023ca8a84462c88d921dad6723f772adf63e24985d3af1aa03363c788e3b2dac4fe57400194ca077255d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
